## Parallel Transport Animation Scratch Ntbk

In [4]:
import numpy as np

v1, v2 = np.array([1, 2]), np.array([2, 1])
A = np.vstack([v1, -v2]).T
A

array([[ 1, -2],
       [ 2, -1]])

In [8]:
np.linalg.inv(A)

array([[-0.33333333,  0.66666667],
       [-0.66666667,  0.33333333]])

In [9]:
v = np.array([2.343, 2134.2])
v.astype(int)

array([   2, 2134])

In [10]:
np.array([[1, 2], [-4, 9]])

array([[ 1,  2],
       [-4,  9]])

In [11]:
tau = np.array([0.3, -0.1])
0 <= tau <= 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [16]:
width, height = 3, 3
z_buff = np.ones([width, height]) * float('inf')
z_buff

array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [18]:
z_buff[0][2] = 1
z_buff

array([[inf, inf,  1.],
       [inf, inf, inf],
       [inf, inf, inf]])

In [20]:
screen_array = np.zeros((height, width, 3), dtype=np.uint8)
screen_array

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [21]:
screen_array[0]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [34]:
width, height = 10, 5
RGB = np.zeros((3, width, height), dtype=np.uint8)
RGB

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=uint8)

In [35]:
import numpy as np
import matplotlib.pyplot as plt

def f(z):
    return -1j * z**2

# Define a grid of complex numbers
x = np.linspace(-2, 2, 100)
y = np.linspace(-2, 2, 100)

X, Y = np.meshgrid(x, y)
Z = X + 1j * Y

# Apply the conformal map
W = f(Z)

# Plot the original grid
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Original Grid")
plt.xlabel("Real")
plt.ylabel("Imaginary")
plt.grid()
plt.scatter(X, Y, s=1, c='k')

# Plot the transformed grid
plt.subplot(1, 2, 2)
plt.title("Transformed Grid")
plt.xlabel("Real")
plt.ylabel("Imaginary")
plt.grid()
plt.scatter(np.real(W), np.imag(W), s=1, c='k')

plt.show()


ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/_c_internal_utils.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/_c_internal_utils.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/_c_internal_utils.cpython-310-darwin.so' (no such file)

In [38]:
width, height = 5, 10
RGB = np.zeros((3, width, height), dtype=np.uint8)
RGB

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=uint8)